//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grades
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<short> Exam1 { get; set; }
        public Nullable<short> Exam2 { get; set; }
        public Nullable<short> Exam3 { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual tbl_lessons tbl_lessons { get; set; }
        public virtual tbl_students tbl_students { get; set; }
    }
}
